title: Tim's homepage for Stats information
description: Bookmark this to keep an eye on my project updates!

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

gem "github-pages", group: :jekyll_plugins # Optionally, if you'd like to preview your site on your computer, add the following to your site's Gemfile:

# Enables a "Download ZIP" button on the site (set to true if you want visitors to download your repository)
show_downloads: false # enable if you have  files that visitors might want to download, or You’re offering datasets, scripts, or templates.

google_analytics: G-ZDLT4GP1SS # Google tracking ID